# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmdir_ <- function(path) {
    invisible(.Call(`_fs_rmdir_`, path))
}

stat_ <- function(path, fail) {
    .Call(`_fs_stat_`, path, fail)
}

unlink_ <- function(path) {
    invisible(.Call(`_fs_unlink_`, path))
}

touch_ <- function(path, atime, mtime) {
    invisible(.Call(`_fs_touch_`, path, atime, mtime))
}

users_ <- function() {
    .Call(`_fs_users_`)
}

tidy_ <- function(path) {
    .Call(`_fs_tidy_`, path)
}

