# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

move_ <- function(path, new_path) {
    invisible(.Call(`_fs_move_`, path, new_path))
}

create_ <- function(path, mode_str) {
    invisible(.Call(`_fs_create_`, path, mode_str))
}

stat_ <- function(path) {
    .Call(`_fs_stat_`, path)
}

access_ <- function(path, mode) {
    .Call(`_fs_access_`, path, mode)
}

chmod_ <- function(path, mode_str) {
    invisible(.Call(`_fs_chmod_`, path, mode_str))
}

getmode_ <- function(mode) {
    .Call(`_fs_getmode_`, mode)
}

strmode_ <- function(mode) {
    .Call(`_fs_strmode_`, mode)
}

link_create_hard_ <- function(path, new_path) {
    invisible(.Call(`_fs_link_create_hard_`, path, new_path))
}

link_create_symbolic_ <- function(path, new_path) {
    invisible(.Call(`_fs_link_create_symbolic_`, path, new_path))
}

normalize_ <- function(path) {
    .Call(`_fs_normalize_`, path)
}

