# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

move_ <- function(path, new_path) {
    invisible(.Call(`_fs_move_`, path, new_path))
}

create_ <- function(path, mode) {
    invisible(.Call(`_fs_create_`, path, mode))
}

access_ <- function(path, mode) {
    .Call(`_fs_access_`, path, mode)
}

normalize_ <- function(path) {
    .Call(`_fs_normalize_`, path)
}

